# Generated by Django 2.2.4 on 2019-08-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'managed': True, 'verbose_name': 'News'},
        ),
    ]
