# Generated by Django 2.2.4 on 2019-08-20 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20190820_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
