# Generated by Django 2.2.4 on 2019-08-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawler', '0006_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('img_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(blank=True)),
            ],
            options={
                'verbose_name': 'News',
                'managed': True,
            },
        ),
    ]
